-- T4 (follow-up): backfill structured opening_hours onto existing activities
-- in the 7 in-scope categories, derived from each row's own free-text `hours`/
-- `opens_time` string in 0002/0008/0011. Only rows with a real open+close time
-- are converted; rows with no time info, or only a one-sided `opens_time`
-- (every bars/nightlife row), are left as-is -- inventing a closing time would
-- show a fabricated Open/Closed status. See engineering-notes.md for the full
-- per-row source mapping.

UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "11:00", "close": "23:00"}, {"day": "tuesday", "open": "11:00", "close": "23:00"}, {"day": "wednesday", "open": "11:00", "close": "23:00"}, {"day": "thursday", "open": "11:00", "close": "23:00"}, {"day": "friday", "open": "11:00", "close": "23:00"}, {"day": "saturday", "open": "11:00", "close": "23:00"}, {"day": "sunday", "open": "11:00", "close": "23:00"}]}}'::jsonb WHERE title = 'Skadarlija Food Walk';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Paris", "always_open": false, "periods": [{"day": "monday", "open": "17:00", "close": "21:00"}, {"day": "tuesday", "open": "17:00", "close": "21:00"}, {"day": "wednesday", "open": "17:00", "close": "21:00"}, {"day": "thursday", "open": "17:00", "close": "21:00"}, {"day": "friday", "open": "17:00", "close": "21:00"}, {"day": "saturday", "open": "17:00", "close": "21:00"}, {"day": "sunday", "open": "17:00", "close": "21:00"}]}}'::jsonb WHERE title = 'Eiffel Tower Sunset Picnic';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Asia/Tokyo", "always_open": false, "periods": [{"day": "monday", "open": "18:00", "close": "01:00"}, {"day": "tuesday", "open": "18:00", "close": "01:00"}, {"day": "wednesday", "open": "18:00", "close": "01:00"}, {"day": "thursday", "open": "18:00", "close": "01:00"}, {"day": "friday", "open": "18:00", "close": "01:00"}, {"day": "saturday", "open": "18:00", "close": "01:00"}, {"day": "sunday", "open": "18:00", "close": "01:00"}]}}'::jsonb WHERE title = 'Shibuya Street Food Crawl';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "11:00", "close": "00:00"}, {"day": "tuesday", "open": "11:00", "close": "00:00"}, {"day": "wednesday", "open": "11:00", "close": "00:00"}, {"day": "thursday", "open": "11:00", "close": "00:00"}, {"day": "friday", "open": "11:00", "close": "00:00"}, {"day": "saturday", "open": "09:00", "close": "00:00"}, {"day": "sunday", "open": "09:00", "close": "00:00"}]}}'::jsonb WHERE title = 'Ambar';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "11:30", "close": "23:00"}, {"day": "tuesday", "open": "11:30", "close": "23:00"}, {"day": "wednesday", "open": "11:30", "close": "23:00"}, {"day": "thursday", "open": "11:30", "close": "23:00"}, {"day": "friday", "open": "11:30", "close": "23:00"}, {"day": "saturday", "open": "11:30", "close": "23:00"}, {"day": "sunday", "open": "11:30", "close": "23:00"}]}}'::jsonb WHERE title = 'Pečat Restoran';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "08:00", "close": "01:00"}, {"day": "tuesday", "open": "08:00", "close": "01:00"}, {"day": "wednesday", "open": "08:00", "close": "01:00"}, {"day": "thursday", "open": "08:00", "close": "01:00"}, {"day": "friday", "open": "08:00", "close": "01:00"}, {"day": "saturday", "open": "08:00", "close": "01:00"}, {"day": "sunday", "open": "10:00", "close": "22:00"}]}}'::jsonb WHERE title = 'Kafana Pavle Korcagin';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "09:00", "close": "23:00"}, {"day": "tuesday", "open": "09:00", "close": "23:00"}, {"day": "wednesday", "open": "09:00", "close": "23:00"}, {"day": "thursday", "open": "09:00", "close": "23:00"}, {"day": "friday", "open": "09:00", "close": "23:00"}, {"day": "saturday", "open": "09:00", "close": "23:00"}, {"day": "sunday", "open": "09:00", "close": "23:00"}]}}'::jsonb WHERE title = 'MAMA''S Bistro';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "tuesday", "open": "09:00", "close": "23:00"}, {"day": "wednesday", "open": "09:00", "close": "23:00"}, {"day": "thursday", "open": "09:00", "close": "23:00"}, {"day": "friday", "open": "09:00", "close": "23:00"}, {"day": "saturday", "open": "09:00", "close": "23:00"}, {"day": "sunday", "open": "09:00", "close": "23:00"}]}}'::jsonb WHERE title = 'Mezestoran Dvorište';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "09:00", "close": "23:00"}, {"day": "tuesday", "open": "09:00", "close": "23:00"}, {"day": "wednesday", "open": "09:00", "close": "23:00"}, {"day": "thursday", "open": "09:00", "close": "23:00"}, {"day": "friday", "open": "09:00", "close": "23:00"}, {"day": "saturday", "open": "09:00", "close": "23:00"}, {"day": "sunday", "open": "09:00", "close": "23:00"}]}}'::jsonb WHERE title = 'Zavicaj Restaurant';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "11:00", "close": "23:00"}, {"day": "tuesday", "open": "11:00", "close": "23:00"}, {"day": "wednesday", "open": "11:00", "close": "23:00"}, {"day": "thursday", "open": "11:00", "close": "23:00"}, {"day": "friday", "open": "11:00", "close": "23:00"}, {"day": "saturday", "open": "11:00", "close": "23:00"}, {"day": "sunday", "open": "11:00", "close": "23:00"}]}}'::jsonb WHERE title = 'Curry Souls';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "tuesday", "open": "10:00", "close": "22:30"}, {"day": "wednesday", "open": "10:00", "close": "22:30"}, {"day": "thursday", "open": "10:00", "close": "22:30"}, {"day": "friday", "open": "10:00", "close": "22:30"}, {"day": "saturday", "open": "10:00", "close": "22:30"}, {"day": "sunday", "open": "10:00", "close": "22:30"}]}}'::jsonb WHERE title = 'Gradska';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "09:00", "close": "20:00"}, {"day": "tuesday", "open": "09:00", "close": "20:00"}, {"day": "wednesday", "open": "09:00", "close": "20:00"}, {"day": "thursday", "open": "09:00", "close": "20:00"}, {"day": "friday", "open": "09:00", "close": "20:00"}, {"day": "saturday", "open": "09:00", "close": "20:00"}, {"day": "sunday", "open": "11:00", "close": "20:00"}]}}'::jsonb WHERE title = 'To Je To';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "11:00", "close": "02:00"}, {"day": "tuesday", "open": "11:00", "close": "02:00"}, {"day": "wednesday", "open": "11:00", "close": "02:00"}, {"day": "thursday", "open": "11:00", "close": "02:00"}, {"day": "friday", "open": "11:00", "close": "02:00"}, {"day": "saturday", "open": "11:00", "close": "02:00"}, {"day": "sunday", "open": "11:00", "close": "02:00"}]}}'::jsonb WHERE title = 'Tri Sesira';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "16:00", "close": "00:00"}, {"day": "tuesday", "open": "16:00", "close": "00:00"}, {"day": "wednesday", "open": "16:00", "close": "00:00"}, {"day": "thursday", "open": "16:00", "close": "00:00"}, {"day": "friday", "open": "16:00", "close": "00:00"}, {"day": "saturday", "open": "16:00", "close": "00:00"}, {"day": "sunday", "open": "16:00", "close": "00:00"}]}}'::jsonb WHERE title = 'Koi Bar • Sushi And Cocktail';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "07:00", "close": "22:00"}, {"day": "tuesday", "open": "07:00", "close": "22:00"}, {"day": "wednesday", "open": "07:00", "close": "22:00"}, {"day": "thursday", "open": "07:00", "close": "22:00"}, {"day": "friday", "open": "07:00", "close": "22:00"}, {"day": "saturday", "open": "07:00", "close": "22:00"}, {"day": "sunday", "open": "07:00", "close": "22:00"}]}}'::jsonb WHERE title = 'Coffee Dictionary Skadarlija';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "08:00", "close": "23:00"}, {"day": "tuesday", "open": "08:00", "close": "23:00"}, {"day": "wednesday", "open": "08:00", "close": "23:00"}, {"day": "thursday", "open": "08:00", "close": "23:00"}, {"day": "friday", "open": "08:00", "close": "23:00"}, {"day": "saturday", "open": "08:00", "close": "23:00"}, {"day": "sunday", "open": "09:00", "close": "23:00"}]}}'::jsonb WHERE title = 'Koffein';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "08:00", "close": "00:00"}, {"day": "tuesday", "open": "08:00", "close": "00:00"}, {"day": "wednesday", "open": "08:00", "close": "00:00"}, {"day": "thursday", "open": "08:00", "close": "00:00"}, {"day": "friday", "open": "08:00", "close": "01:00"}, {"day": "saturday", "open": "08:00", "close": "01:00"}, {"day": "sunday", "open": "08:00", "close": "01:00"}]}}'::jsonb WHERE title = 'Coffee Dream Dorćol';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "07:00", "close": "00:00"}, {"day": "tuesday", "open": "07:00", "close": "00:00"}, {"day": "wednesday", "open": "07:00", "close": "00:00"}, {"day": "thursday", "open": "07:00", "close": "00:00"}, {"day": "friday", "open": "07:00", "close": "00:00"}, {"day": "saturday", "open": "07:00", "close": "00:00"}, {"day": "sunday", "open": "07:00", "close": "00:00"}]}}'::jsonb WHERE title = 'Cafe Moskva';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": true, "periods": []}}'::jsonb WHERE title = 'NEGRO caffe';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "07:00", "close": "21:00"}, {"day": "tuesday", "open": "07:00", "close": "21:00"}, {"day": "wednesday", "open": "07:00", "close": "21:00"}, {"day": "thursday", "open": "07:00", "close": "21:00"}, {"day": "friday", "open": "07:00", "close": "21:00"}, {"day": "saturday", "open": "09:00", "close": "17:00"}, {"day": "sunday", "open": "09:00", "close": "17:00"}]}}'::jsonb WHERE title = 'uzitak coffee selection and delights';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "09:00", "close": "23:00"}, {"day": "tuesday", "open": "09:00", "close": "23:00"}, {"day": "wednesday", "open": "09:00", "close": "23:00"}, {"day": "thursday", "open": "09:00", "close": "23:00"}, {"day": "friday", "open": "09:00", "close": "23:00"}, {"day": "saturday", "open": "09:00", "close": "23:00"}, {"day": "sunday", "open": "09:00", "close": "23:00"}]}}'::jsonb WHERE title = 'Coffee Room Serbia';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": true, "periods": []}}'::jsonb WHERE title = 'Kafe Supa';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "08:00", "close": "00:00"}, {"day": "tuesday", "open": "08:00", "close": "00:00"}, {"day": "wednesday", "open": "08:00", "close": "00:00"}, {"day": "thursday", "open": "08:00", "close": "00:00"}, {"day": "friday", "open": "08:00", "close": "00:00"}, {"day": "saturday", "open": "08:00", "close": "00:00"}, {"day": "sunday", "open": "08:00", "close": "00:00"}]}}'::jsonb WHERE title = 'Cafe&Factory';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "08:00", "close": "20:00"}, {"day": "tuesday", "open": "08:00", "close": "20:00"}, {"day": "wednesday", "open": "08:00", "close": "20:00"}, {"day": "thursday", "open": "08:00", "close": "20:00"}, {"day": "friday", "open": "08:00", "close": "20:00"}, {"day": "saturday", "open": "08:00", "close": "20:00"}, {"day": "sunday", "open": "08:00", "close": "20:00"}]}}'::jsonb WHERE title = 'Belgrade Fortress & Kalemegdan Park';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Rome", "always_open": false, "periods": [{"day": "monday", "open": "09:00", "close": "19:00"}, {"day": "tuesday", "open": "09:00", "close": "19:00"}, {"day": "wednesday", "open": "09:00", "close": "19:00"}, {"day": "thursday", "open": "09:00", "close": "19:00"}, {"day": "friday", "open": "09:00", "close": "19:00"}, {"day": "saturday", "open": "09:00", "close": "19:00"}, {"day": "sunday", "open": "09:00", "close": "19:00"}]}}'::jsonb WHERE title = 'Colosseum Guided Tour';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "tuesday", "open": "10:00", "close": "20:00"}, {"day": "wednesday", "open": "10:00", "close": "20:00"}, {"day": "thursday", "open": "10:00", "close": "20:00"}, {"day": "friday", "open": "10:00", "close": "20:00"}, {"day": "saturday", "open": "10:00", "close": "20:00"}, {"day": "sunday", "open": "10:00", "close": "20:00"}, {"day": "monday", "open": "10:00", "close": "18:00"}]}}'::jsonb WHERE title = 'Nikola Tesla Museum';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "08:00", "close": "20:00"}, {"day": "tuesday", "open": "08:00", "close": "20:00"}, {"day": "wednesday", "open": "08:00", "close": "20:00"}, {"day": "thursday", "open": "08:00", "close": "20:00"}, {"day": "friday", "open": "08:00", "close": "20:00"}, {"day": "saturday", "open": "08:00", "close": "20:00"}, {"day": "sunday", "open": "08:00", "close": "20:00"}]}}'::jsonb WHERE title = 'Church of Saint Sava';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": true, "periods": []}}'::jsonb WHERE title = 'Republic Square';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "wednesday", "open": "10:00", "close": "18:00"}, {"day": "friday", "open": "10:00", "close": "18:00"}, {"day": "sunday", "open": "10:00", "close": "18:00"}, {"day": "monday", "open": "10:00", "close": "18:00"}, {"day": "thursday", "open": "12:00", "close": "20:00"}, {"day": "saturday", "open": "12:00", "close": "20:00"}]}}'::jsonb WHERE title = 'National Museum Belgrade';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "09:00", "close": "19:00"}, {"day": "tuesday", "open": "09:00", "close": "19:00"}, {"day": "wednesday", "open": "09:00", "close": "19:00"}, {"day": "thursday", "open": "09:00", "close": "19:00"}, {"day": "friday", "open": "09:00", "close": "19:00"}, {"day": "saturday", "open": "09:00", "close": "19:00"}, {"day": "sunday", "open": "09:00", "close": "19:00"}]}}'::jsonb WHERE title = 'Nebojša Tower';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": true, "periods": []}}'::jsonb WHERE title = 'Street Art Tour Savamala';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Madrid", "always_open": false, "periods": [{"day": "monday", "open": "09:00", "close": "18:00"}, {"day": "tuesday", "open": "09:00", "close": "18:00"}, {"day": "wednesday", "open": "09:00", "close": "18:00"}, {"day": "thursday", "open": "09:00", "close": "18:00"}, {"day": "friday", "open": "09:00", "close": "18:00"}, {"day": "saturday", "open": "09:00", "close": "18:00"}, {"day": "sunday", "open": "09:00", "close": "18:00"}]}}'::jsonb WHERE title = 'Sagrada Familia Art Walk';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "wednesday", "open": "11:00", "close": "19:00"}, {"day": "friday", "open": "11:00", "close": "19:00"}, {"day": "sunday", "open": "11:00", "close": "19:00"}, {"day": "monday", "open": "11:00", "close": "19:00"}, {"day": "thursday", "open": "11:00", "close": "20:00"}, {"day": "saturday", "open": "11:00", "close": "20:00"}]}}'::jsonb WHERE title = 'Museum of Contemporary Art Belgrade';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "11:00", "close": "20:00"}, {"day": "tuesday", "open": "11:00", "close": "20:00"}, {"day": "wednesday", "open": "11:00", "close": "20:00"}, {"day": "thursday", "open": "11:00", "close": "20:00"}, {"day": "friday", "open": "11:00", "close": "20:00"}, {"day": "saturday", "open": "11:00", "close": "15:00"}]}}'::jsonb WHERE title = 'Art for All';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "14:00", "close": "20:00"}, {"day": "tuesday", "open": "14:00", "close": "20:00"}, {"day": "wednesday", "open": "14:00", "close": "20:00"}, {"day": "thursday", "open": "14:00", "close": "20:00"}, {"day": "friday", "open": "14:00", "close": "20:00"}, {"day": "saturday", "open": "11:00", "close": "15:00"}]}}'::jsonb WHERE title = 'Green Door - Gallery & Art Gift Shop';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "10:00", "close": "18:00"}, {"day": "tuesday", "open": "10:00", "close": "18:00"}, {"day": "wednesday", "open": "10:00", "close": "18:00"}, {"day": "thursday", "open": "10:00", "close": "18:00"}, {"day": "friday", "open": "10:00", "close": "18:00"}, {"day": "saturday", "open": "10:00", "close": "18:00"}, {"day": "sunday", "open": "10:00", "close": "18:00"}]}}'::jsonb WHERE title = 'Eugster Belgrade';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "wednesday", "open": "12:00", "close": "20:00"}]}}'::jsonb WHERE title = 'O3ONE Art Space';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "10:00", "close": "21:00"}, {"day": "tuesday", "open": "10:00", "close": "21:00"}, {"day": "wednesday", "open": "10:00", "close": "21:00"}, {"day": "thursday", "open": "10:00", "close": "21:00"}, {"day": "friday", "open": "10:00", "close": "21:00"}, {"day": "saturday", "open": "10:00", "close": "21:00"}, {"day": "sunday", "open": "10:00", "close": "21:00"}]}}'::jsonb WHERE title = 'Knez Mihailova Shopping Walk';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "10:00", "close": "22:00"}, {"day": "tuesday", "open": "10:00", "close": "22:00"}, {"day": "wednesday", "open": "10:00", "close": "22:00"}, {"day": "thursday", "open": "10:00", "close": "22:00"}, {"day": "friday", "open": "10:00", "close": "22:00"}, {"day": "saturday", "open": "10:00", "close": "22:00"}, {"day": "sunday", "open": "10:00", "close": "22:00"}]}}'::jsonb WHERE title = 'UŠĆE Shopping Center';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "10:00", "close": "22:00"}, {"day": "tuesday", "open": "10:00", "close": "22:00"}, {"day": "wednesday", "open": "10:00", "close": "22:00"}, {"day": "thursday", "open": "10:00", "close": "22:00"}, {"day": "friday", "open": "10:00", "close": "22:00"}, {"day": "saturday", "open": "10:00", "close": "22:00"}, {"day": "sunday", "open": "10:00", "close": "22:00"}]}}'::jsonb WHERE title = 'Delta City';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "10:00", "close": "22:00"}, {"day": "tuesday", "open": "10:00", "close": "22:00"}, {"day": "wednesday", "open": "10:00", "close": "22:00"}, {"day": "thursday", "open": "10:00", "close": "22:00"}, {"day": "friday", "open": "10:00", "close": "22:00"}, {"day": "saturday", "open": "10:00", "close": "22:00"}, {"day": "sunday", "open": "10:00", "close": "22:00"}]}}'::jsonb WHERE title = 'Big Fashion';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "10:00", "close": "22:00"}, {"day": "tuesday", "open": "10:00", "close": "22:00"}, {"day": "wednesday", "open": "10:00", "close": "22:00"}, {"day": "thursday", "open": "10:00", "close": "22:00"}, {"day": "friday", "open": "10:00", "close": "22:00"}, {"day": "saturday", "open": "10:00", "close": "22:00"}, {"day": "sunday", "open": "10:00", "close": "22:00"}]}}'::jsonb WHERE title = 'Rajiceva Shopping Center';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "06:00", "close": "17:00"}, {"day": "tuesday", "open": "06:00", "close": "17:00"}, {"day": "wednesday", "open": "06:00", "close": "17:00"}, {"day": "thursday", "open": "06:00", "close": "17:00"}, {"day": "friday", "open": "06:00", "close": "17:00"}, {"day": "saturday", "open": "06:00", "close": "17:00"}, {"day": "sunday", "open": "06:00", "close": "17:00"}]}}'::jsonb WHERE title = 'Kalenić Pijaca';
UPDATE activities SET details = details || '{"opening_hours": {"timezone": "Europe/Belgrade", "always_open": false, "periods": [{"day": "monday", "open": "08:00", "close": "22:00"}, {"day": "tuesday", "open": "08:00", "close": "22:00"}, {"day": "wednesday", "open": "08:00", "close": "22:00"}, {"day": "thursday", "open": "08:00", "close": "22:00"}, {"day": "friday", "open": "08:00", "close": "22:00"}, {"day": "saturday", "open": "08:00", "close": "22:00"}, {"day": "sunday", "open": "08:00", "close": "22:00"}]}}'::jsonb WHERE title = 'Mercator Center Belgrade';

