// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/activities/v1/activities.proto

package activitiesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivitiesService_QueryActivities_FullMethodName = "/activities.v1.ActivitiesService/QueryActivities"
	ActivitiesService_SuggestCities_FullMethodName   = "/activities.v1.ActivitiesService/SuggestCities"
)

// ActivitiesServiceClient is the client API for ActivitiesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ActivitiesService owns the activity catalog and answers scoped, filtered
// queries against it. Stateless about users: callers supply whatever
// location context a scope needs on every request.
type ActivitiesServiceClient interface {
	QueryActivities(ctx context.Context, in *QueryActivitiesRequest, opts ...grpc.CallOption) (*QueryActivitiesResponse, error)
	// SuggestCities powers the Anywhere city typeahead: a prefix match over
	// the catalog's own cities (T1's city column), not a live geocoding call.
	SuggestCities(ctx context.Context, in *SuggestCitiesRequest, opts ...grpc.CallOption) (*SuggestCitiesResponse, error)
}

type activitiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivitiesServiceClient(cc grpc.ClientConnInterface) ActivitiesServiceClient {
	return &activitiesServiceClient{cc}
}

func (c *activitiesServiceClient) QueryActivities(ctx context.Context, in *QueryActivitiesRequest, opts ...grpc.CallOption) (*QueryActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryActivitiesResponse)
	err := c.cc.Invoke(ctx, ActivitiesService_QueryActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesServiceClient) SuggestCities(ctx context.Context, in *SuggestCitiesRequest, opts ...grpc.CallOption) (*SuggestCitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestCitiesResponse)
	err := c.cc.Invoke(ctx, ActivitiesService_SuggestCities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivitiesServiceServer is the server API for ActivitiesService service.
// All implementations must embed UnimplementedActivitiesServiceServer
// for forward compatibility.
//
// ActivitiesService owns the activity catalog and answers scoped, filtered
// queries against it. Stateless about users: callers supply whatever
// location context a scope needs on every request.
type ActivitiesServiceServer interface {
	QueryActivities(context.Context, *QueryActivitiesRequest) (*QueryActivitiesResponse, error)
	// SuggestCities powers the Anywhere city typeahead: a prefix match over
	// the catalog's own cities (T1's city column), not a live geocoding call.
	SuggestCities(context.Context, *SuggestCitiesRequest) (*SuggestCitiesResponse, error)
	mustEmbedUnimplementedActivitiesServiceServer()
}

// UnimplementedActivitiesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivitiesServiceServer struct{}

func (UnimplementedActivitiesServiceServer) QueryActivities(context.Context, *QueryActivitiesRequest) (*QueryActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryActivities not implemented")
}
func (UnimplementedActivitiesServiceServer) SuggestCities(context.Context, *SuggestCitiesRequest) (*SuggestCitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestCities not implemented")
}
func (UnimplementedActivitiesServiceServer) mustEmbedUnimplementedActivitiesServiceServer() {}
func (UnimplementedActivitiesServiceServer) testEmbeddedByValue()                           {}

// UnsafeActivitiesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivitiesServiceServer will
// result in compilation errors.
type UnsafeActivitiesServiceServer interface {
	mustEmbedUnimplementedActivitiesServiceServer()
}

func RegisterActivitiesServiceServer(s grpc.ServiceRegistrar, srv ActivitiesServiceServer) {
	// If the following call pancis, it indicates UnimplementedActivitiesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivitiesService_ServiceDesc, srv)
}

func _ActivitiesService_QueryActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).QueryActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivitiesService_QueryActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).QueryActivities(ctx, req.(*QueryActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitiesService_SuggestCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).SuggestCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivitiesService_SuggestCities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).SuggestCities(ctx, req.(*SuggestCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivitiesService_ServiceDesc is the grpc.ServiceDesc for ActivitiesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivitiesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activities.v1.ActivitiesService",
	HandlerType: (*ActivitiesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryActivities",
			Handler:    _ActivitiesService_QueryActivities_Handler,
		},
		{
			MethodName: "SuggestCities",
			Handler:    _ActivitiesService_SuggestCities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/activities/v1/activities.proto",
}
