// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/activities/v1/activities.proto

package activitiesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope int32

const (
	Scope_SCOPE_UNSPECIFIED Scope = 0
	// Activities within the service's configured radius of home_location.
	Scope_SCOPE_HOME Scope = 1
	// Activities within the service's configured radius of current_location.
	Scope_SCOPE_NEARBY Scope = 2
	// Activities whose country differs from home_country.
	Scope_SCOPE_OUTSIDE_COUNTRY Scope = 3
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		1: "SCOPE_HOME",
		2: "SCOPE_NEARBY",
		3: "SCOPE_OUTSIDE_COUNTRY",
	}
	Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED":     0,
		"SCOPE_HOME":            1,
		"SCOPE_NEARBY":          2,
		"SCOPE_OUTSIDE_COUNTRY": 3,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activities_v1_activities_proto_enumTypes[0].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_proto_activities_v1_activities_proto_enumTypes[0]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{0}
}

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED                Category = 0
	Category_CATEGORY_FOOD_AND_DRINK             Category = 1
	Category_CATEGORY_HISTORY_AND_CULTURE        Category = 2
	Category_CATEGORY_NATURE_AND_OUTDOORS        Category = 3
	Category_CATEGORY_ART_AND_DESIGN             Category = 4
	Category_CATEGORY_SPORTS                     Category = 5
	Category_CATEGORY_ENTERTAINMENT_AND_WELLNESS Category = 6
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_FOOD_AND_DRINK",
		2: "CATEGORY_HISTORY_AND_CULTURE",
		3: "CATEGORY_NATURE_AND_OUTDOORS",
		4: "CATEGORY_ART_AND_DESIGN",
		5: "CATEGORY_SPORTS",
		6: "CATEGORY_ENTERTAINMENT_AND_WELLNESS",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED":                0,
		"CATEGORY_FOOD_AND_DRINK":             1,
		"CATEGORY_HISTORY_AND_CULTURE":        2,
		"CATEGORY_NATURE_AND_OUTDOORS":        3,
		"CATEGORY_ART_AND_DESIGN":             4,
		"CATEGORY_SPORTS":                     5,
		"CATEGORY_ENTERTAINMENT_AND_WELLNESS": 6,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activities_v1_activities_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_proto_activities_v1_activities_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{1}
}

type PriceTier int32

const (
	PriceTier_PRICE_TIER_UNSPECIFIED PriceTier = 0
	PriceTier_PRICE_TIER_BUDGET      PriceTier = 1
	PriceTier_PRICE_TIER_MODERATE    PriceTier = 2
	PriceTier_PRICE_TIER_PREMIUM     PriceTier = 3
	PriceTier_PRICE_TIER_LUXURY      PriceTier = 4
)

// Enum value maps for PriceTier.
var (
	PriceTier_name = map[int32]string{
		0: "PRICE_TIER_UNSPECIFIED",
		1: "PRICE_TIER_BUDGET",
		2: "PRICE_TIER_MODERATE",
		3: "PRICE_TIER_PREMIUM",
		4: "PRICE_TIER_LUXURY",
	}
	PriceTier_value = map[string]int32{
		"PRICE_TIER_UNSPECIFIED": 0,
		"PRICE_TIER_BUDGET":      1,
		"PRICE_TIER_MODERATE":    2,
		"PRICE_TIER_PREMIUM":     3,
		"PRICE_TIER_LUXURY":      4,
	}
)

func (x PriceTier) Enum() *PriceTier {
	p := new(PriceTier)
	*p = x
	return p
}

func (x PriceTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceTier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activities_v1_activities_proto_enumTypes[2].Descriptor()
}

func (PriceTier) Type() protoreflect.EnumType {
	return &file_proto_activities_v1_activities_proto_enumTypes[2]
}

func (x PriceTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceTier.Descriptor instead.
func (PriceTier) EnumDescriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{2}
}

type Sort int32

const (
	Sort_SORT_UNSPECIFIED Sort = 0
	// Highest rating first, deterministic tie-break by title. The accepted
	// "top activities" MVP ranking; only valid for SCOPE_OUTSIDE_COUNTRY.
	Sort_SORT_TOP_RATED Sort = 1
)

// Enum value maps for Sort.
var (
	Sort_name = map[int32]string{
		0: "SORT_UNSPECIFIED",
		1: "SORT_TOP_RATED",
	}
	Sort_value = map[string]int32{
		"SORT_UNSPECIFIED": 0,
		"SORT_TOP_RATED":   1,
	}
)

func (x Sort) Enum() *Sort {
	p := new(Sort)
	*p = x
	return p
}

func (x Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activities_v1_activities_proto_enumTypes[3].Descriptor()
}

func (Sort) Type() protoreflect.EnumType {
	return &file_proto_activities_v1_activities_proto_enumTypes[3]
}

func (x Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sort.Descriptor instead.
func (Sort) EnumDescriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{3}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type QueryActivitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope Scope                  `protobuf:"varint,1,opt,name=scope,proto3,enum=activities.v1.Scope" json:"scope,omitempty"`
	// Required when scope == SCOPE_NEARBY.
	CurrentLocation *Location `protobuf:"bytes,2,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	// Required when scope == SCOPE_HOME.
	HomeLocation *Location `protobuf:"bytes,3,opt,name=home_location,json=homeLocation,proto3" json:"home_location,omitempty"`
	// Required when scope == SCOPE_OUTSIDE_COUNTRY.
	HomeCountry string `protobuf:"bytes,4,opt,name=home_country,json=homeCountry,proto3" json:"home_country,omitempty"`
	// Filters, all optional, combined as AND. An unfiltered request returns
	// all in-scope activities.
	Categories []Category `protobuf:"varint,5,rep,packed,name=categories,proto3,enum=activities.v1.Category" json:"categories,omitempty"`          // OR within this field.
	PriceTier  PriceTier  `protobuf:"varint,6,opt,name=price_tier,json=priceTier,proto3,enum=activities.v1.PriceTier" json:"price_tier,omitempty"` // PRICE_TIER_UNSPECIFIED = no filter.
	MinRating  float64    `protobuf:"fixed64,7,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`                             // 0 = no filter.
	// Further narrows the scope radius (SCOPE_HOME / SCOPE_NEARBY only).
	// 0 = no filter. Setting it for SCOPE_OUTSIDE_COUNTRY is a validation error.
	MaxDistanceKm float64 `protobuf:"fixed64,8,opt,name=max_distance_km,json=maxDistanceKm,proto3" json:"max_distance_km,omitempty"`
	// Requests a specific result ordering. SORT_UNSPECIFIED = no explicit
	// ordering requested. SORT_TOP_RATED is only valid for
	// SCOPE_OUTSIDE_COUNTRY; setting it for SCOPE_HOME/SCOPE_NEARBY is a
	// validation error.
	Sort          Sort `protobuf:"varint,9,opt,name=sort,proto3,enum=activities.v1.Sort" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActivitiesRequest) Reset() {
	*x = QueryActivitiesRequest{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivitiesRequest) ProtoMessage() {}

func (x *QueryActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivitiesRequest.ProtoReflect.Descriptor instead.
func (*QueryActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{1}
}

func (x *QueryActivitiesRequest) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_UNSPECIFIED
}

func (x *QueryActivitiesRequest) GetCurrentLocation() *Location {
	if x != nil {
		return x.CurrentLocation
	}
	return nil
}

func (x *QueryActivitiesRequest) GetHomeLocation() *Location {
	if x != nil {
		return x.HomeLocation
	}
	return nil
}

func (x *QueryActivitiesRequest) GetHomeCountry() string {
	if x != nil {
		return x.HomeCountry
	}
	return ""
}

func (x *QueryActivitiesRequest) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *QueryActivitiesRequest) GetPriceTier() PriceTier {
	if x != nil {
		return x.PriceTier
	}
	return PriceTier_PRICE_TIER_UNSPECIFIED
}

func (x *QueryActivitiesRequest) GetMinRating() float64 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *QueryActivitiesRequest) GetMaxDistanceKm() float64 {
	if x != nil {
		return x.MaxDistanceKm
	}
	return 0
}

func (x *QueryActivitiesRequest) GetSort() Sort {
	if x != nil {
		return x.Sort
	}
	return Sort_SORT_UNSPECIFIED
}

type Activity struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category    Category               `protobuf:"varint,4,opt,name=category,proto3,enum=activities.v1.Category" json:"category,omitempty"`
	Location    *Location              `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Country     string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	PriceTier   PriceTier              `protobuf:"varint,7,opt,name=price_tier,json=priceTier,proto3,enum=activities.v1.PriceTier" json:"price_tier,omitempty"`
	Rating      float64                `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	ImageRefs   []string               `protobuf:"bytes,9,rep,name=image_refs,json=imageRefs,proto3" json:"image_refs,omitempty"`
	Tags        []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	// Distance from the request's reference location, in kilometers.
	// Only populated for SCOPE_HOME / SCOPE_NEARBY; 0 otherwise.
	DistanceKm    float64 `protobuf:"fixed64,11,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{2}
}

func (x *Activity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Activity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Activity) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Activity) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Activity) GetPriceTier() PriceTier {
	if x != nil {
		return x.PriceTier
	}
	return PriceTier_PRICE_TIER_UNSPECIFIED
}

func (x *Activity) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Activity) GetImageRefs() []string {
	if x != nil {
		return x.ImageRefs
	}
	return nil
}

func (x *Activity) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Activity) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type QueryActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActivitiesResponse) Reset() {
	*x = QueryActivitiesResponse{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivitiesResponse) ProtoMessage() {}

func (x *QueryActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivitiesResponse.ProtoReflect.Descriptor instead.
func (*QueryActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{3}
}

func (x *QueryActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

var File_proto_activities_v1_activities_proto protoreflect.FileDescriptor

const file_proto_activities_v1_activities_proto_rawDesc = "" +
	"\n" +
	"$proto/activities/v1/activities.proto\x12\ractivities.v1\".\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"\xcb\x03\n" +
	"\x16QueryActivitiesRequest\x12*\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x14.activities.v1.ScopeR\x05scope\x12B\n" +
	"\x10current_location\x18\x02 \x01(\v2\x17.activities.v1.LocationR\x0fcurrentLocation\x12<\n" +
	"\rhome_location\x18\x03 \x01(\v2\x17.activities.v1.LocationR\fhomeLocation\x12!\n" +
	"\fhome_country\x18\x04 \x01(\tR\vhomeCountry\x127\n" +
	"\n" +
	"categories\x18\x05 \x03(\x0e2\x17.activities.v1.CategoryR\n" +
	"categories\x127\n" +
	"\n" +
	"price_tier\x18\x06 \x01(\x0e2\x18.activities.v1.PriceTierR\tpriceTier\x12\x1d\n" +
	"\n" +
	"min_rating\x18\a \x01(\x01R\tminRating\x12&\n" +
	"\x0fmax_distance_km\x18\b \x01(\x01R\rmaxDistanceKm\x12'\n" +
	"\x04sort\x18\t \x01(\x0e2\x13.activities.v1.SortR\x04sort\"\xfb\x02\n" +
	"\bActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x17.activities.v1.CategoryR\bcategory\x123\n" +
	"\blocation\x18\x05 \x01(\v2\x17.activities.v1.LocationR\blocation\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x127\n" +
	"\n" +
	"price_tier\x18\a \x01(\x0e2\x18.activities.v1.PriceTierR\tpriceTier\x12\x16\n" +
	"\x06rating\x18\b \x01(\x01R\x06rating\x12\x1d\n" +
	"\n" +
	"image_refs\x18\t \x03(\tR\timageRefs\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1f\n" +
	"\vdistance_km\x18\v \x01(\x01R\n" +
	"distanceKm\"R\n" +
	"\x17QueryActivitiesResponse\x127\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x17.activities.v1.ActivityR\n" +
	"activities*[\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SCOPE_HOME\x10\x01\x12\x10\n" +
	"\fSCOPE_NEARBY\x10\x02\x12\x19\n" +
	"\x15SCOPE_OUTSIDE_COUNTRY\x10\x03*\xe0\x01\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CATEGORY_FOOD_AND_DRINK\x10\x01\x12 \n" +
	"\x1cCATEGORY_HISTORY_AND_CULTURE\x10\x02\x12 \n" +
	"\x1cCATEGORY_NATURE_AND_OUTDOORS\x10\x03\x12\x1b\n" +
	"\x17CATEGORY_ART_AND_DESIGN\x10\x04\x12\x13\n" +
	"\x0fCATEGORY_SPORTS\x10\x05\x12'\n" +
	"#CATEGORY_ENTERTAINMENT_AND_WELLNESS\x10\x06*\x86\x01\n" +
	"\tPriceTier\x12\x1a\n" +
	"\x16PRICE_TIER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRICE_TIER_BUDGET\x10\x01\x12\x17\n" +
	"\x13PRICE_TIER_MODERATE\x10\x02\x12\x16\n" +
	"\x12PRICE_TIER_PREMIUM\x10\x03\x12\x15\n" +
	"\x11PRICE_TIER_LUXURY\x10\x04*0\n" +
	"\x04Sort\x12\x14\n" +
	"\x10SORT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_TOP_RATED\x10\x012u\n" +
	"\x11ActivitiesService\x12`\n" +
	"\x0fQueryActivities\x12%.activities.v1.QueryActivitiesRequest\x1a&.activities.v1.QueryActivitiesResponseB1Z/backend/shared/proto/activities/v1;activitiesv1b\x06proto3"

var (
	file_proto_activities_v1_activities_proto_rawDescOnce sync.Once
	file_proto_activities_v1_activities_proto_rawDescData []byte
)

func file_proto_activities_v1_activities_proto_rawDescGZIP() []byte {
	file_proto_activities_v1_activities_proto_rawDescOnce.Do(func() {
		file_proto_activities_v1_activities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_activities_v1_activities_proto_rawDesc), len(file_proto_activities_v1_activities_proto_rawDesc)))
	})
	return file_proto_activities_v1_activities_proto_rawDescData
}

var file_proto_activities_v1_activities_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_activities_v1_activities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_activities_v1_activities_proto_goTypes = []any{
	(Scope)(0),                      // 0: activities.v1.Scope
	(Category)(0),                   // 1: activities.v1.Category
	(PriceTier)(0),                  // 2: activities.v1.PriceTier
	(Sort)(0),                       // 3: activities.v1.Sort
	(*Location)(nil),                // 4: activities.v1.Location
	(*QueryActivitiesRequest)(nil),  // 5: activities.v1.QueryActivitiesRequest
	(*Activity)(nil),                // 6: activities.v1.Activity
	(*QueryActivitiesResponse)(nil), // 7: activities.v1.QueryActivitiesResponse
}
var file_proto_activities_v1_activities_proto_depIdxs = []int32{
	0,  // 0: activities.v1.QueryActivitiesRequest.scope:type_name -> activities.v1.Scope
	4,  // 1: activities.v1.QueryActivitiesRequest.current_location:type_name -> activities.v1.Location
	4,  // 2: activities.v1.QueryActivitiesRequest.home_location:type_name -> activities.v1.Location
	1,  // 3: activities.v1.QueryActivitiesRequest.categories:type_name -> activities.v1.Category
	2,  // 4: activities.v1.QueryActivitiesRequest.price_tier:type_name -> activities.v1.PriceTier
	3,  // 5: activities.v1.QueryActivitiesRequest.sort:type_name -> activities.v1.Sort
	1,  // 6: activities.v1.Activity.category:type_name -> activities.v1.Category
	4,  // 7: activities.v1.Activity.location:type_name -> activities.v1.Location
	2,  // 8: activities.v1.Activity.price_tier:type_name -> activities.v1.PriceTier
	6,  // 9: activities.v1.QueryActivitiesResponse.activities:type_name -> activities.v1.Activity
	5,  // 10: activities.v1.ActivitiesService.QueryActivities:input_type -> activities.v1.QueryActivitiesRequest
	7,  // 11: activities.v1.ActivitiesService.QueryActivities:output_type -> activities.v1.QueryActivitiesResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_activities_v1_activities_proto_init() }
func file_proto_activities_v1_activities_proto_init() {
	if File_proto_activities_v1_activities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_activities_v1_activities_proto_rawDesc), len(file_proto_activities_v1_activities_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_activities_v1_activities_proto_goTypes,
		DependencyIndexes: file_proto_activities_v1_activities_proto_depIdxs,
		EnumInfos:         file_proto_activities_v1_activities_proto_enumTypes,
		MessageInfos:      file_proto_activities_v1_activities_proto_msgTypes,
	}.Build()
	File_proto_activities_v1_activities_proto = out.File
	file_proto_activities_v1_activities_proto_goTypes = nil
	file_proto_activities_v1_activities_proto_depIdxs = nil
}
