// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/activities/v1/activities.proto

package activitiesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope int32

const (
	Scope_SCOPE_UNSPECIFIED Scope = 0
	// Activities within the service's configured radius of current_location.
	Scope_SCOPE_NEARBY Scope = 2
	// Broad exploration anchored to current_location when supplied. With
	// max_distance_km set, narrows to that radius; otherwise unfiltered by
	// distance ("truly anywhere").
	Scope_SCOPE_ANYWHERE Scope = 4
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		2: "SCOPE_NEARBY",
		4: "SCOPE_ANYWHERE",
	}
	Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED": 0,
		"SCOPE_NEARBY":      2,
		"SCOPE_ANYWHERE":    4,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activities_v1_activities_proto_enumTypes[0].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_proto_activities_v1_activities_proto_enumTypes[0]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{0}
}

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED                Category = 0
	Category_CATEGORY_FOOD_AND_DRINK             Category = 1
	Category_CATEGORY_HISTORY_AND_CULTURE        Category = 2
	Category_CATEGORY_NATURE_AND_OUTDOORS        Category = 3
	Category_CATEGORY_ART_AND_DESIGN             Category = 4
	Category_CATEGORY_SPORTS                     Category = 5
	Category_CATEGORY_ENTERTAINMENT_AND_WELLNESS Category = 6
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_FOOD_AND_DRINK",
		2: "CATEGORY_HISTORY_AND_CULTURE",
		3: "CATEGORY_NATURE_AND_OUTDOORS",
		4: "CATEGORY_ART_AND_DESIGN",
		5: "CATEGORY_SPORTS",
		6: "CATEGORY_ENTERTAINMENT_AND_WELLNESS",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED":                0,
		"CATEGORY_FOOD_AND_DRINK":             1,
		"CATEGORY_HISTORY_AND_CULTURE":        2,
		"CATEGORY_NATURE_AND_OUTDOORS":        3,
		"CATEGORY_ART_AND_DESIGN":             4,
		"CATEGORY_SPORTS":                     5,
		"CATEGORY_ENTERTAINMENT_AND_WELLNESS": 6,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activities_v1_activities_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_proto_activities_v1_activities_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{1}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

// Photo is a single activity photo, sourced from Google Places and resolved
// once at seed/build time (never a live per-request Places call). Author
// attribution travels with the photo wherever it's shown, per Google's
// mandatory attribution policy; author/author_link are empty for a photo
// that hasn't been resolved yet (falls back to the missing-image state
// client-side rather than a placeholder).
type Photo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	AuthorLink    string                 `protobuf:"bytes,3,opt,name=author_link,json=authorLink,proto3" json:"author_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photo) Reset() {
	*x = Photo{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{1}
}

func (x *Photo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Photo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Photo) GetAuthorLink() string {
	if x != nil {
		return x.AuthorLink
	}
	return ""
}

type QueryActivitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope Scope                  `protobuf:"varint,1,opt,name=scope,proto3,enum=activities.v1.Scope" json:"scope,omitempty"`
	// Required when scope == SCOPE_NEARBY. Optional for SCOPE_ANYWHERE: when
	// absent, anywhere returns broadly with no distance filter.
	CurrentLocation *Location `protobuf:"bytes,2,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	// Filters, all optional, combined as AND. An unfiltered request returns
	// all in-scope activities.
	Categories []Category `protobuf:"varint,5,rep,packed,name=categories,proto3,enum=activities.v1.Category" json:"categories,omitempty"` // OR within this field.
	MinRating  float64    `protobuf:"fixed64,7,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`                    // 0 = no filter.
	// Narrows results to within this radius of current_location, or (for
	// SCOPE_ANYWHERE) of the nearest entry in cities. 0 = no filter
	// (SCOPE_NEARBY still applies its configured default radius; SCOPE_ANYWHERE
	// returns unfiltered by distance, i.e. "truly anywhere"). Requires
	// current_location or a non-empty cities to be set; SCOPE_ANYWHERE accepts
	// any positive value (not capped to SCOPE_NEARBY's configured radius).
	MaxDistanceKm float64 `protobuf:"fixed64,8,opt,name=max_distance_km,json=maxDistanceKm,proto3" json:"max_distance_km,omitempty"`
	// SCOPE_ANYWHERE only: zero or more city centroids (resolved client-side,
	// e.g. from a typeahead) to anchor the search on instead of
	// current_location. When set, results are the union of activities within
	// max_distance_km of ANY listed city, and current_location is ignored for
	// filtering purposes.
	Cities        []*Location `protobuf:"bytes,10,rep,name=cities,proto3" json:"cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActivitiesRequest) Reset() {
	*x = QueryActivitiesRequest{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivitiesRequest) ProtoMessage() {}

func (x *QueryActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivitiesRequest.ProtoReflect.Descriptor instead.
func (*QueryActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{2}
}

func (x *QueryActivitiesRequest) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_UNSPECIFIED
}

func (x *QueryActivitiesRequest) GetCurrentLocation() *Location {
	if x != nil {
		return x.CurrentLocation
	}
	return nil
}

func (x *QueryActivitiesRequest) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *QueryActivitiesRequest) GetMinRating() float64 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *QueryActivitiesRequest) GetMaxDistanceKm() float64 {
	if x != nil {
		return x.MaxDistanceKm
	}
	return 0
}

func (x *QueryActivitiesRequest) GetCities() []*Location {
	if x != nil {
		return x.Cities
	}
	return nil
}

type Activity struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category    Category               `protobuf:"varint,4,opt,name=category,proto3,enum=activities.v1.Category" json:"category,omitempty"`
	Location    *Location              `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Country     string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Rating      float64                `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Photos      []*Photo               `protobuf:"bytes,9,rep,name=photos,proto3" json:"photos,omitempty"`
	Tags        []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	// Distance from the request's reference location, in kilometers. Only
	// populated when the request scope had a reference point (SCOPE_NEARBY
	// always; SCOPE_ANYWHERE when current_location was supplied); 0 otherwise.
	DistanceKm    float64 `protobuf:"fixed64,11,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{3}
}

func (x *Activity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Activity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Activity) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Activity) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Activity) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Activity) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Activity) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Activity) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

type QueryActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActivitiesResponse) Reset() {
	*x = QueryActivitiesResponse{}
	mi := &file_proto_activities_v1_activities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivitiesResponse) ProtoMessage() {}

func (x *QueryActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activities_v1_activities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivitiesResponse.ProtoReflect.Descriptor instead.
func (*QueryActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_activities_v1_activities_proto_rawDescGZIP(), []int{4}
}

func (x *QueryActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

var File_proto_activities_v1_activities_proto protoreflect.FileDescriptor

const file_proto_activities_v1_activities_proto_rawDesc = "" +
	"\n" +
	"$proto/activities/v1/activities.proto\x12\ractivities.v1\".\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"R\n" +
	"\x05Photo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1f\n" +
	"\vauthor_link\x18\x03 \x01(\tR\n" +
	"authorLink\"\xf4\x02\n" +
	"\x16QueryActivitiesRequest\x12*\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x14.activities.v1.ScopeR\x05scope\x12B\n" +
	"\x10current_location\x18\x02 \x01(\v2\x17.activities.v1.LocationR\x0fcurrentLocation\x127\n" +
	"\n" +
	"categories\x18\x05 \x03(\x0e2\x17.activities.v1.CategoryR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"min_rating\x18\a \x01(\x01R\tminRating\x12&\n" +
	"\x0fmax_distance_km\x18\b \x01(\x01R\rmaxDistanceKm\x12/\n" +
	"\x06cities\x18\n" +
	" \x03(\v2\x17.activities.v1.LocationR\x06citiesJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x06\x10\aJ\x04\b\t\x10\n" +
	"R\rhome_locationR\fhome_countryR\x04sort\"\xd7\x02\n" +
	"\bActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x17.activities.v1.CategoryR\bcategory\x123\n" +
	"\blocation\x18\x05 \x01(\v2\x17.activities.v1.LocationR\blocation\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x16\n" +
	"\x06rating\x18\b \x01(\x01R\x06rating\x12,\n" +
	"\x06photos\x18\t \x03(\v2\x14.activities.v1.PhotoR\x06photos\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1f\n" +
	"\vdistance_km\x18\v \x01(\x01R\n" +
	"distanceKmJ\x04\b\a\x10\b\"R\n" +
	"\x17QueryActivitiesResponse\x127\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x17.activities.v1.ActivityR\n" +
	"activities*s\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSCOPE_NEARBY\x10\x02\x12\x12\n" +
	"\x0eSCOPE_ANYWHERE\x10\x04\"\x04\b\x01\x10\x01\"\x04\b\x03\x10\x03*\n" +
	"SCOPE_HOME*\x15SCOPE_OUTSIDE_COUNTRY*\xe0\x01\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CATEGORY_FOOD_AND_DRINK\x10\x01\x12 \n" +
	"\x1cCATEGORY_HISTORY_AND_CULTURE\x10\x02\x12 \n" +
	"\x1cCATEGORY_NATURE_AND_OUTDOORS\x10\x03\x12\x1b\n" +
	"\x17CATEGORY_ART_AND_DESIGN\x10\x04\x12\x13\n" +
	"\x0fCATEGORY_SPORTS\x10\x05\x12'\n" +
	"#CATEGORY_ENTERTAINMENT_AND_WELLNESS\x10\x062u\n" +
	"\x11ActivitiesService\x12`\n" +
	"\x0fQueryActivities\x12%.activities.v1.QueryActivitiesRequest\x1a&.activities.v1.QueryActivitiesResponseB1Z/backend/shared/proto/activities/v1;activitiesv1b\x06proto3"

var (
	file_proto_activities_v1_activities_proto_rawDescOnce sync.Once
	file_proto_activities_v1_activities_proto_rawDescData []byte
)

func file_proto_activities_v1_activities_proto_rawDescGZIP() []byte {
	file_proto_activities_v1_activities_proto_rawDescOnce.Do(func() {
		file_proto_activities_v1_activities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_activities_v1_activities_proto_rawDesc), len(file_proto_activities_v1_activities_proto_rawDesc)))
	})
	return file_proto_activities_v1_activities_proto_rawDescData
}

var file_proto_activities_v1_activities_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_activities_v1_activities_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_activities_v1_activities_proto_goTypes = []any{
	(Scope)(0),                      // 0: activities.v1.Scope
	(Category)(0),                   // 1: activities.v1.Category
	(*Location)(nil),                // 2: activities.v1.Location
	(*Photo)(nil),                   // 3: activities.v1.Photo
	(*QueryActivitiesRequest)(nil),  // 4: activities.v1.QueryActivitiesRequest
	(*Activity)(nil),                // 5: activities.v1.Activity
	(*QueryActivitiesResponse)(nil), // 6: activities.v1.QueryActivitiesResponse
}
var file_proto_activities_v1_activities_proto_depIdxs = []int32{
	0, // 0: activities.v1.QueryActivitiesRequest.scope:type_name -> activities.v1.Scope
	2, // 1: activities.v1.QueryActivitiesRequest.current_location:type_name -> activities.v1.Location
	1, // 2: activities.v1.QueryActivitiesRequest.categories:type_name -> activities.v1.Category
	2, // 3: activities.v1.QueryActivitiesRequest.cities:type_name -> activities.v1.Location
	1, // 4: activities.v1.Activity.category:type_name -> activities.v1.Category
	2, // 5: activities.v1.Activity.location:type_name -> activities.v1.Location
	3, // 6: activities.v1.Activity.photos:type_name -> activities.v1.Photo
	5, // 7: activities.v1.QueryActivitiesResponse.activities:type_name -> activities.v1.Activity
	4, // 8: activities.v1.ActivitiesService.QueryActivities:input_type -> activities.v1.QueryActivitiesRequest
	6, // 9: activities.v1.ActivitiesService.QueryActivities:output_type -> activities.v1.QueryActivitiesResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_activities_v1_activities_proto_init() }
func file_proto_activities_v1_activities_proto_init() {
	if File_proto_activities_v1_activities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_activities_v1_activities_proto_rawDesc), len(file_proto_activities_v1_activities_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_activities_v1_activities_proto_goTypes,
		DependencyIndexes: file_proto_activities_v1_activities_proto_depIdxs,
		EnumInfos:         file_proto_activities_v1_activities_proto_enumTypes,
		MessageInfos:      file_proto_activities_v1_activities_proto_msgTypes,
	}.Build()
	File_proto_activities_v1_activities_proto = out.File
	file_proto_activities_v1_activities_proto_goTypes = nil
	file_proto_activities_v1_activities_proto_depIdxs = nil
}
