// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: activities/v1/activities.proto

package activitiesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope int32

const (
	Scope_SCOPE_UNSPECIFIED Scope = 0
	// Activities within the service's configured radius of current_location.
	Scope_SCOPE_NEARBY Scope = 2
	// Broad exploration anchored to current_location when supplied. With
	// max_distance_km set, narrows to that radius; otherwise unfiltered by
	// distance ("truly anywhere").
	Scope_SCOPE_ANYWHERE Scope = 4
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		2: "SCOPE_NEARBY",
		4: "SCOPE_ANYWHERE",
	}
	Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED": 0,
		"SCOPE_NEARBY":      2,
		"SCOPE_ANYWHERE":    4,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_activities_v1_activities_proto_enumTypes[0].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_activities_v1_activities_proto_enumTypes[0]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{0}
}

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED       Category = 0
	Category_CATEGORY_RESTAURANTS       Category = 1
	Category_CATEGORY_CAFES             Category = 2
	Category_CATEGORY_BARS              Category = 3
	Category_CATEGORY_NIGHTLIFE         Category = 4
	Category_CATEGORY_NATURE            Category = 5
	Category_CATEGORY_SPORT             Category = 6
	Category_CATEGORY_KIDS              Category = 7
	Category_CATEGORY_CULTURE           Category = 8
	Category_CATEGORY_ART               Category = 9
	Category_CATEGORY_WELLNESS          Category = 10
	Category_CATEGORY_SHOPPING          Category = 11
	Category_CATEGORY_ENTERTAINMENT     Category = 12
	Category_CATEGORY_TOURS_EXPERIENCES Category = 13
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0:  "CATEGORY_UNSPECIFIED",
		1:  "CATEGORY_RESTAURANTS",
		2:  "CATEGORY_CAFES",
		3:  "CATEGORY_BARS",
		4:  "CATEGORY_NIGHTLIFE",
		5:  "CATEGORY_NATURE",
		6:  "CATEGORY_SPORT",
		7:  "CATEGORY_KIDS",
		8:  "CATEGORY_CULTURE",
		9:  "CATEGORY_ART",
		10: "CATEGORY_WELLNESS",
		11: "CATEGORY_SHOPPING",
		12: "CATEGORY_ENTERTAINMENT",
		13: "CATEGORY_TOURS_EXPERIENCES",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED":       0,
		"CATEGORY_RESTAURANTS":       1,
		"CATEGORY_CAFES":             2,
		"CATEGORY_BARS":              3,
		"CATEGORY_NIGHTLIFE":         4,
		"CATEGORY_NATURE":            5,
		"CATEGORY_SPORT":             6,
		"CATEGORY_KIDS":              7,
		"CATEGORY_CULTURE":           8,
		"CATEGORY_ART":               9,
		"CATEGORY_WELLNESS":          10,
		"CATEGORY_SHOPPING":          11,
		"CATEGORY_ENTERTAINMENT":     12,
		"CATEGORY_TOURS_EXPERIENCES": 13,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_activities_v1_activities_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_activities_v1_activities_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{1}
}

// ActivityStatus (T1) is an activity's catalog lifecycle state. Only
// ACTIVITY_STATUS_PUBLISHED activities are ever returned by
// QueryActivities, the public app-facing RPC — draft/pending exist for the
// admin surface (T2) to read and write.
type ActivityStatus int32

const (
	ActivityStatus_ACTIVITY_STATUS_UNSPECIFIED ActivityStatus = 0
	ActivityStatus_ACTIVITY_STATUS_PUBLISHED   ActivityStatus = 1
	ActivityStatus_ACTIVITY_STATUS_DRAFT       ActivityStatus = 2
	ActivityStatus_ACTIVITY_STATUS_PENDING     ActivityStatus = 3
)

// Enum value maps for ActivityStatus.
var (
	ActivityStatus_name = map[int32]string{
		0: "ACTIVITY_STATUS_UNSPECIFIED",
		1: "ACTIVITY_STATUS_PUBLISHED",
		2: "ACTIVITY_STATUS_DRAFT",
		3: "ACTIVITY_STATUS_PENDING",
	}
	ActivityStatus_value = map[string]int32{
		"ACTIVITY_STATUS_UNSPECIFIED": 0,
		"ACTIVITY_STATUS_PUBLISHED":   1,
		"ACTIVITY_STATUS_DRAFT":       2,
		"ACTIVITY_STATUS_PENDING":     3,
	}
)

func (x ActivityStatus) Enum() *ActivityStatus {
	p := new(ActivityStatus)
	*p = x
	return p
}

func (x ActivityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_activities_v1_activities_proto_enumTypes[2].Descriptor()
}

func (ActivityStatus) Type() protoreflect.EnumType {
	return &file_activities_v1_activities_proto_enumTypes[2]
}

func (x ActivityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityStatus.Descriptor instead.
func (ActivityStatus) EnumDescriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{2}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_activities_v1_activities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

// Photo is a single activity photo, sourced from Google Places and resolved
// once — either at seed/build time, or live on first detail view via
// GetActivityPhotos (T2), which persists the result so every later request
// is cache-only. Author
// attribution travels with the photo wherever it's shown, per Google's
// mandatory attribution policy; author/author_link are empty for a photo
// that hasn't been resolved yet (falls back to the missing-image state
// client-side rather than a placeholder).
type Photo struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Url        string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Author     string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	AuthorLink string                 `protobuf:"bytes,3,opt,name=author_link,json=authorLink,proto3" json:"author_link,omitempty"`
	// thumb_url and caption are T1 additions: an uploaded photo (as opposed to
	// a Google-sourced one) gets a real 256px thumbnail at an explicit URL
	// (never derived by a naming convention) and an optional caption,
	// independent of attribution. Both are empty for a Google-sourced photo.
	ThumbUrl string `protobuf:"bytes,4,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"`
	Caption  string `protobuf:"bytes,5,opt,name=caption,proto3" json:"caption,omitempty"`
	// provider is the raw activitiessvc.Provider string ("google",
	// "tripadvisor", "admin", "user"). Only a "google" photo gets the
	// Google-Photos-style attribution caption client-side — Tripadvisor's
	// author field holds the reviewer's username, not a Google Photos
	// contributor, and must not be rendered the same way.
	Provider      string `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photo) Reset() {
	*x = Photo{}
	mi := &file_activities_v1_activities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{1}
}

func (x *Photo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Photo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Photo) GetAuthorLink() string {
	if x != nil {
		return x.AuthorLink
	}
	return ""
}

func (x *Photo) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

func (x *Photo) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Photo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type QueryActivitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope Scope                  `protobuf:"varint,1,opt,name=scope,proto3,enum=activities.v1.Scope" json:"scope,omitempty"`
	// Required when scope == SCOPE_NEARBY. Optional for SCOPE_ANYWHERE: when
	// absent, anywhere returns broadly with no distance filter.
	CurrentLocation *Location `protobuf:"bytes,2,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	// Filters, all optional, combined as AND. An unfiltered request returns
	// all in-scope activities.
	Categories []Category `protobuf:"varint,5,rep,packed,name=categories,proto3,enum=activities.v1.Category" json:"categories,omitempty"` // OR within this field.
	MinRating  float64    `protobuf:"fixed64,7,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`                    // 0 = no filter.
	// Narrows results to within this radius of current_location, or (for
	// SCOPE_ANYWHERE) of the nearest entry in cities. 0 = no filter
	// (SCOPE_NEARBY still applies its configured default radius; SCOPE_ANYWHERE
	// returns unfiltered by distance, i.e. "truly anywhere"). Requires
	// current_location or a non-empty cities to be set; SCOPE_ANYWHERE accepts
	// any positive value (not capped to SCOPE_NEARBY's configured radius).
	MaxDistanceKm float64 `protobuf:"fixed64,8,opt,name=max_distance_km,json=maxDistanceKm,proto3" json:"max_distance_km,omitempty"`
	// SCOPE_ANYWHERE only: zero or more city centroids (resolved client-side,
	// e.g. from a typeahead) to anchor the search on instead of
	// current_location. When set, results are the union of activities within
	// max_distance_km of ANY listed city, and current_location is ignored for
	// filtering purposes.
	Cities []*Location `protobuf:"bytes,10,rep,name=cities,proto3" json:"cities,omitempty"`
	// Narrows results to activities whose subcategory is any of these
	// (T1), OR'd within the field and AND-ed with categories above. Slugs
	// from activitiessvc.Subcategories; empty = no filter.
	Subcategories []string `protobuf:"bytes,11,rep,name=subcategories,proto3" json:"subcategories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActivitiesRequest) Reset() {
	*x = QueryActivitiesRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivitiesRequest) ProtoMessage() {}

func (x *QueryActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivitiesRequest.ProtoReflect.Descriptor instead.
func (*QueryActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{2}
}

func (x *QueryActivitiesRequest) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_UNSPECIFIED
}

func (x *QueryActivitiesRequest) GetCurrentLocation() *Location {
	if x != nil {
		return x.CurrentLocation
	}
	return nil
}

func (x *QueryActivitiesRequest) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *QueryActivitiesRequest) GetMinRating() float64 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *QueryActivitiesRequest) GetMaxDistanceKm() float64 {
	if x != nil {
		return x.MaxDistanceKm
	}
	return 0
}

func (x *QueryActivitiesRequest) GetCities() []*Location {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *QueryActivitiesRequest) GetSubcategories() []string {
	if x != nil {
		return x.Subcategories
	}
	return nil
}

type Activity struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category    Category               `protobuf:"varint,4,opt,name=category,proto3,enum=activities.v1.Category" json:"category,omitempty"`
	Location    *Location              `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Country     string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Rating      float64                `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Photos      []*Photo               `protobuf:"bytes,9,rep,name=photos,proto3" json:"photos,omitempty"`
	Tags        []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	// Distance from the request's reference location, in kilometers. Only
	// populated when the request scope had a reference point (SCOPE_NEARBY
	// always; SCOPE_ANYWHERE when current_location was supplied); 0 otherwise.
	DistanceKm float64 `protobuf:"fixed64,11,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	// Category-specific structured detail payload (T2), JSON-encoded (a
	// decoded JSON object per APP_STANDARDS.md's per-category field table,
	// e.g. {"cuisine": "Italian", "popular_dishes": [...]});
	// "{}" when the category has no detail data. A JSON string rather than
	// 13 proto messages: the app renders it generically off a data-driven
	// config, not 13 typed screens.
	Details string `protobuf:"bytes,12,opt,name=details,proto3" json:"details,omitempty"`
	// city, address, and status are T1 additions: city was already a DB
	// column (unexposed on the wire before now); address is new. Both are
	// empty when unset. status is always ACTIVITY_STATUS_PUBLISHED on
	// QueryActivities responses (see ActivityStatus above); exposed here as
	// a real field for the admin surface (T2), which reads/writes all three.
	City    string         `protobuf:"bytes,13,opt,name=city,proto3" json:"city,omitempty"`
	Address string         `protobuf:"bytes,14,opt,name=address,proto3" json:"address,omitempty"`
	Status  ActivityStatus `protobuf:"varint,15,opt,name=status,proto3,enum=activities.v1.ActivityStatus" json:"status,omitempty"`
	// subcategory (T1) is an optional, category-validated subtype slug
	// (activitiessvc.Subcategories), e.g. "fine_dining" under "restaurants".
	// "" = not set; always valid.
	Subcategory string `protobuf:"bytes,16,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	// google_reviews, review_count, and google_maps_uri (T3,
	// places-live-details) are only ever populated on a
	// GetActivityWithLiveDetails response for a Places-sourced row — always
	// empty/0 on QueryActivities/GetActivity, since neither is ever stored.
	// review_count is Google's live userRatingCount, merged alongside rating
	// above. google_maps_uri is the mandatory "View on Google Maps"
	// attribution link target (Places API attribution policy).
	GoogleReviews []*GoogleReview `protobuf:"bytes,17,rep,name=google_reviews,json=googleReviews,proto3" json:"google_reviews,omitempty"`
	ReviewCount   int32           `protobuf:"varint,18,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	GoogleMapsUri string          `protobuf:"bytes,19,opt,name=google_maps_uri,json=googleMapsUri,proto3" json:"google_maps_uri,omitempty"`
	// created_at (T3, admin-activities-schema-resync) is the row's creation
	// timestamp, RFC3339-formatted — the `activities.created_at` DB column
	// (NOT NULL DEFAULT now()), selected for the first time by this field.
	CreatedAt     string `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_activities_v1_activities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{3}
}

func (x *Activity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Activity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Activity) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Activity) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Activity) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Activity) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Activity) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Activity) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *Activity) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Activity) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Activity) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Activity) GetStatus() ActivityStatus {
	if x != nil {
		return x.Status
	}
	return ActivityStatus_ACTIVITY_STATUS_UNSPECIFIED
}

func (x *Activity) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

func (x *Activity) GetGoogleReviews() []*GoogleReview {
	if x != nil {
		return x.GoogleReviews
	}
	return nil
}

func (x *Activity) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *Activity) GetGoogleMapsUri() string {
	if x != nil {
		return x.GoogleMapsUri
	}
	return ""
}

func (x *Activity) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// GoogleAuthorAttribution is the Places API's mandatory per-review
// attribution (T3, places-live-details) — avatar, display name, profile
// link. photo_uri is "" when Google returned no reviewer avatar.
type GoogleAuthorAttribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PhotoUri      string                 `protobuf:"bytes,2,opt,name=photo_uri,json=photoUri,proto3" json:"photo_uri,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleAuthorAttribution) Reset() {
	*x = GoogleAuthorAttribution{}
	mi := &file_activities_v1_activities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleAuthorAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleAuthorAttribution) ProtoMessage() {}

func (x *GoogleAuthorAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleAuthorAttribution.ProtoReflect.Descriptor instead.
func (*GoogleAuthorAttribution) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{4}
}

func (x *GoogleAuthorAttribution) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GoogleAuthorAttribution) GetPhotoUri() string {
	if x != nil {
		return x.PhotoUri
	}
	return ""
}

func (x *GoogleAuthorAttribution) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// GoogleReview is one live Google Place Details review (T3,
// places-live-details), merged onto Activity.google_reviews on detail-page
// open for a Places-sourced row; never persisted. publish_time is Places'
// raw timestamp string, not pre-formatted — the client formats it for
// display.
type GoogleReview struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	AuthorAttribution *GoogleAuthorAttribution `protobuf:"bytes,1,opt,name=author_attribution,json=authorAttribution,proto3" json:"author_attribution,omitempty"`
	Rating            float64                  `protobuf:"fixed64,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Text              string                   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	PublishTime       string                   `protobuf:"bytes,4,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GoogleReview) Reset() {
	*x = GoogleReview{}
	mi := &file_activities_v1_activities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleReview) ProtoMessage() {}

func (x *GoogleReview) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleReview.ProtoReflect.Descriptor instead.
func (*GoogleReview) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{5}
}

func (x *GoogleReview) GetAuthorAttribution() *GoogleAuthorAttribution {
	if x != nil {
		return x.AuthorAttribution
	}
	return nil
}

func (x *GoogleReview) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GoogleReview) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GoogleReview) GetPublishTime() string {
	if x != nil {
		return x.PublishTime
	}
	return ""
}

type QueryActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryActivitiesResponse) Reset() {
	*x = QueryActivitiesResponse{}
	mi := &file_activities_v1_activities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActivitiesResponse) ProtoMessage() {}

func (x *QueryActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActivitiesResponse.ProtoReflect.Descriptor instead.
func (*QueryActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{6}
}

func (x *QueryActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

type SuggestCitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Free-text prefix, e.g. "Bar". Empty or non-matching yields an empty
	// suggestions list, never an error.
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestCitiesRequest) Reset() {
	*x = SuggestCitiesRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestCitiesRequest) ProtoMessage() {}

func (x *SuggestCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestCitiesRequest.ProtoReflect.Descriptor instead.
func (*SuggestCitiesRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestCitiesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type CitySuggestion struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	City    string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// Centroid of the city's activities, usable directly as a "cities" entry
	// in a follow-up QueryActivitiesRequest.
	Centroid      *Location `protobuf:"bytes,3,opt,name=centroid,proto3" json:"centroid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CitySuggestion) Reset() {
	*x = CitySuggestion{}
	mi := &file_activities_v1_activities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CitySuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitySuggestion) ProtoMessage() {}

func (x *CitySuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitySuggestion.ProtoReflect.Descriptor instead.
func (*CitySuggestion) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{8}
}

func (x *CitySuggestion) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CitySuggestion) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CitySuggestion) GetCentroid() *Location {
	if x != nil {
		return x.Centroid
	}
	return nil
}

type SuggestCitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []*CitySuggestion      `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestCitiesResponse) Reset() {
	*x = SuggestCitiesResponse{}
	mi := &file_activities_v1_activities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestCitiesResponse) ProtoMessage() {}

func (x *SuggestCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestCitiesResponse.ProtoReflect.Descriptor instead.
func (*SuggestCitiesResponse) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{9}
}

func (x *SuggestCitiesResponse) GetSuggestions() []*CitySuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

// ListActivitiesRequest is the admin list query (T2). All filters are
// optional and combined as AND; UNSPECIFIED enum values / empty strings mean
// "no filter on this field" — unlike QueryActivitiesRequest, this list is
// never restricted to published-only (the admin needs to see drafts and
// pending rows).
type ListActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`                                              // case-insensitive substring match on title
	Category      Category               `protobuf:"varint,2,opt,name=category,proto3,enum=activities.v1.Category" json:"category,omitempty"`   // CATEGORY_UNSPECIFIED = no filter
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`                                        // "" = no filter
	Status        ActivityStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=activities.v1.ActivityStatus" json:"status,omitempty"` // ACTIVITY_STATUS_UNSPECIFIED = no filter
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`                                       // <= 0 treated as 1
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`               // <= 0 treated as the service default; always clamped to [1, 100] server-side
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesRequest) Reset() {
	*x = ListActivitiesRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesRequest) ProtoMessage() {}

func (x *ListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{10}
}

func (x *ListActivitiesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListActivitiesRequest) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *ListActivitiesRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListActivitiesRequest) GetStatus() ActivityStatus {
	if x != nil {
		return x.Status
	}
	return ActivityStatus_ACTIVITY_STATUS_UNSPECIFIED
}

func (x *ListActivitiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListActivitiesStats counts the whole catalog, ignoring ListActivitiesRequest's
// filters — it backs the admin panel's global stat cards.
type ListActivitiesStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Published     int32                  `protobuf:"varint,2,opt,name=published,proto3" json:"published,omitempty"`
	Draft         int32                  `protobuf:"varint,3,opt,name=draft,proto3" json:"draft,omitempty"`
	Pending       int32                  `protobuf:"varint,4,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesStats) Reset() {
	*x = ListActivitiesStats{}
	mi := &file_activities_v1_activities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesStats) ProtoMessage() {}

func (x *ListActivitiesStats) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesStats.ProtoReflect.Descriptor instead.
func (*ListActivitiesStats) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{11}
}

func (x *ListActivitiesStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListActivitiesStats) GetPublished() int32 {
	if x != nil {
		return x.Published
	}
	return 0
}

func (x *ListActivitiesStats) GetDraft() int32 {
	if x != nil {
		return x.Draft
	}
	return 0
}

func (x *ListActivitiesStats) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type ListActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // count matching the request's filters (for pagination)
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Stats         *ListActivitiesStats   `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesResponse) Reset() {
	*x = ListActivitiesResponse{}
	mi := &file_activities_v1_activities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesResponse) ProtoMessage() {}

func (x *ListActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ListActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{12}
}

func (x *ListActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ListActivitiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListActivitiesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivitiesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListActivitiesResponse) GetStats() *ListActivitiesStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityRequest) Reset() {
	*x = GetActivityRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityRequest) ProtoMessage() {}

func (x *GetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityRequest.ProtoReflect.Descriptor instead.
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{13}
}

func (x *GetActivityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetActivityPhotosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityPhotosRequest) Reset() {
	*x = GetActivityPhotosRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityPhotosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityPhotosRequest) ProtoMessage() {}

func (x *GetActivityPhotosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityPhotosRequest.ProtoReflect.Descriptor instead.
func (*GetActivityPhotosRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{14}
}

func (x *GetActivityPhotosRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetActivityPhotosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photos        []*Photo               `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityPhotosResponse) Reset() {
	*x = GetActivityPhotosResponse{}
	mi := &file_activities_v1_activities_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityPhotosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityPhotosResponse) ProtoMessage() {}

func (x *GetActivityPhotosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityPhotosResponse.ProtoReflect.Descriptor instead.
func (*GetActivityPhotosResponse) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{15}
}

func (x *GetActivityPhotosResponse) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

type ListAdminCitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminCitiesRequest) Reset() {
	*x = ListAdminCitiesRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminCitiesRequest) ProtoMessage() {}

func (x *ListAdminCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminCitiesRequest.ProtoReflect.Descriptor instead.
func (*ListAdminCitiesRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{16}
}

type ListAdminCitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        []string               `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"` // sorted, distinct, never null (empty list, not an error, when the catalog has none)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminCitiesResponse) Reset() {
	*x = ListAdminCitiesResponse{}
	mi := &file_activities_v1_activities_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminCitiesResponse) ProtoMessage() {}

func (x *ListAdminCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminCitiesResponse.ProtoReflect.Descriptor instead.
func (*ListAdminCitiesResponse) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{17}
}

func (x *ListAdminCitiesResponse) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

// UploadPhotoRequest carries the raw, still-encoded (JPEG/PNG) bytes of one
// admin-uploaded photo (T1) — data is capped by proxy-service's
// http.MaxBytesReader (8MB) before it ever reaches this RPC; server/client
// MaxRecvMsgSize/MaxSendMsgSize are raised to 12MB (payload + headroom) to
// carry it.
type UploadPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPhotoRequest) Reset() {
	*x = UploadPhotoRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPhotoRequest) ProtoMessage() {}

func (x *UploadPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPhotoRequest.ProtoReflect.Descriptor instead.
func (*UploadPhotoRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{18}
}

func (x *UploadPhotoRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *UploadPhotoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadPhotoResponse is the pair of URLs proxy-service's public
// http.FileServer over /data/photos serves — the main downscaled photo
// (2000px longest edge) and its thumbnail (256px longest edge).
type UploadPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ThumbUrl      string                 `protobuf:"bytes,2,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPhotoResponse) Reset() {
	*x = UploadPhotoResponse{}
	mi := &file_activities_v1_activities_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPhotoResponse) ProtoMessage() {}

func (x *UploadPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPhotoResponse.ProtoReflect.Descriptor instead.
func (*UploadPhotoResponse) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{19}
}

func (x *UploadPhotoResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadPhotoResponse) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

type CreateActivityRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Title       string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Category    Category               `protobuf:"varint,2,opt,name=category,proto3,enum=activities.v1.Category" json:"category,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	City        string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Address     string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	// ACTIVITY_STATUS_UNSPECIFIED defaults to ACTIVITY_STATUS_DRAFT.
	Status  ActivityStatus `protobuf:"varint,6,opt,name=status,proto3,enum=activities.v1.ActivityStatus" json:"status,omitempty"`
	Details string         `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"` // JSON string, "" = no detail data
	Photos  []*Photo       `protobuf:"bytes,8,rep,name=photos,proto3" json:"photos,omitempty"`
	// subcategory (T1) is optional, validated against category server-side; a
	// mismatch is rejected InvalidArgument. "" is always valid.
	Subcategory   string `protobuf:"bytes,9,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{20}
}

func (x *CreateActivityRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateActivityRequest) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *CreateActivityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateActivityRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateActivityRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateActivityRequest) GetStatus() ActivityStatus {
	if x != nil {
		return x.Status
	}
	return ActivityStatus_ACTIVITY_STATUS_UNSPECIFIED
}

func (x *CreateActivityRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *CreateActivityRequest) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *CreateActivityRequest) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

// PhotoList wraps the one repeated field UpdateActivityRequest needs
// optional (proto3 doesn't allow the `optional` keyword on repeated fields);
// a nil PhotoList means "leave photos untouched", a non-nil one (even with
// zero photos) means "replace with this list".
type PhotoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Photos        []*Photo               `protobuf:"bytes,1,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoList) Reset() {
	*x = PhotoList{}
	mi := &file_activities_v1_activities_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoList) ProtoMessage() {}

func (x *PhotoList) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoList.ProtoReflect.Descriptor instead.
func (*PhotoList) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{21}
}

func (x *PhotoList) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

// UpdateActivityRequest is a partial update (T2): every field below is
// `optional`, so the generated Has*() accessor distinguishes "absent, leave
// untouched" from "present" (including present-and-empty-string) the same
// way proxy-service's JSON pointer fields do on the HTTP side.
type UpdateActivityRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category    *Category              `protobuf:"varint,4,opt,name=category,proto3,enum=activities.v1.Category,oneof" json:"category,omitempty"`
	City        *string                `protobuf:"bytes,5,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Address     *string                `protobuf:"bytes,6,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Status      *ActivityStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=activities.v1.ActivityStatus,oneof" json:"status,omitempty"`
	Details     *string                `protobuf:"bytes,8,opt,name=details,proto3,oneof" json:"details,omitempty"`
	Photos      *PhotoList             `protobuf:"bytes,9,opt,name=photos,proto3" json:"photos,omitempty"`
	// subcategory (T1): same optional/category-validated semantics as
	// CreateActivityRequest's field. `optional` distinguishes "absent, leave
	// untouched" from "present" (including present-and-empty, i.e. clear it).
	Subcategory   *string `protobuf:"bytes,10,opt,name=subcategory,proto3,oneof" json:"subcategory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityRequest) Reset() {
	*x = UpdateActivityRequest{}
	mi := &file_activities_v1_activities_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityRequest) ProtoMessage() {}

func (x *UpdateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activities_v1_activities_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityRequest.ProtoReflect.Descriptor instead.
func (*UpdateActivityRequest) Descriptor() ([]byte, []int) {
	return file_activities_v1_activities_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateActivityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateActivityRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateActivityRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateActivityRequest) GetCategory() Category {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *UpdateActivityRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateActivityRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateActivityRequest) GetStatus() ActivityStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ActivityStatus_ACTIVITY_STATUS_UNSPECIFIED
}

func (x *UpdateActivityRequest) GetDetails() string {
	if x != nil && x.Details != nil {
		return *x.Details
	}
	return ""
}

func (x *UpdateActivityRequest) GetPhotos() *PhotoList {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *UpdateActivityRequest) GetSubcategory() string {
	if x != nil && x.Subcategory != nil {
		return *x.Subcategory
	}
	return ""
}

var File_activities_v1_activities_proto protoreflect.FileDescriptor

const file_activities_v1_activities_proto_rawDesc = "" +
	"\n" +
	"\x1eactivities/v1/activities.proto\x12\ractivities.v1\".\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"\xa5\x01\n" +
	"\x05Photo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1f\n" +
	"\vauthor_link\x18\x03 \x01(\tR\n" +
	"authorLink\x12\x1b\n" +
	"\tthumb_url\x18\x04 \x01(\tR\bthumbUrl\x12\x18\n" +
	"\acaption\x18\x05 \x01(\tR\acaption\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\"\x9a\x03\n" +
	"\x16QueryActivitiesRequest\x12*\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x14.activities.v1.ScopeR\x05scope\x12B\n" +
	"\x10current_location\x18\x02 \x01(\v2\x17.activities.v1.LocationR\x0fcurrentLocation\x127\n" +
	"\n" +
	"categories\x18\x05 \x03(\x0e2\x17.activities.v1.CategoryR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"min_rating\x18\a \x01(\x01R\tminRating\x12&\n" +
	"\x0fmax_distance_km\x18\b \x01(\x01R\rmaxDistanceKm\x12/\n" +
	"\x06cities\x18\n" +
	" \x03(\v2\x17.activities.v1.LocationR\x06cities\x12$\n" +
	"\rsubcategories\x18\v \x03(\tR\rsubcategoriesJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x06\x10\aJ\x04\b\t\x10\n" +
	"R\rhome_locationR\fhome_countryR\x04sort\"\xa6\x05\n" +
	"\bActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x17.activities.v1.CategoryR\bcategory\x123\n" +
	"\blocation\x18\x05 \x01(\v2\x17.activities.v1.LocationR\blocation\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x16\n" +
	"\x06rating\x18\b \x01(\x01R\x06rating\x12,\n" +
	"\x06photos\x18\t \x03(\v2\x14.activities.v1.PhotoR\x06photos\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1f\n" +
	"\vdistance_km\x18\v \x01(\x01R\n" +
	"distanceKm\x12\x18\n" +
	"\adetails\x18\f \x01(\tR\adetails\x12\x12\n" +
	"\x04city\x18\r \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x0e \x01(\tR\aaddress\x125\n" +
	"\x06status\x18\x0f \x01(\x0e2\x1d.activities.v1.ActivityStatusR\x06status\x12 \n" +
	"\vsubcategory\x18\x10 \x01(\tR\vsubcategory\x12B\n" +
	"\x0egoogle_reviews\x18\x11 \x03(\v2\x1b.activities.v1.GoogleReviewR\rgoogleReviews\x12!\n" +
	"\freview_count\x18\x12 \x01(\x05R\vreviewCount\x12&\n" +
	"\x0fgoogle_maps_uri\x18\x13 \x01(\tR\rgoogleMapsUri\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tR\tcreatedAtJ\x04\b\a\x10\b\"k\n" +
	"\x17GoogleAuthorAttribution\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tphoto_uri\x18\x02 \x01(\tR\bphotoUri\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\"\xb4\x01\n" +
	"\fGoogleReview\x12U\n" +
	"\x12author_attribution\x18\x01 \x01(\v2&.activities.v1.GoogleAuthorAttributionR\x11authorAttribution\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x01R\x06rating\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12!\n" +
	"\fpublish_time\x18\x04 \x01(\tR\vpublishTime\"R\n" +
	"\x17QueryActivitiesResponse\x127\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x17.activities.v1.ActivityR\n" +
	"activities\",\n" +
	"\x14SuggestCitiesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"s\n" +
	"\x0eCitySuggestion\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x123\n" +
	"\bcentroid\x18\x03 \x01(\v2\x17.activities.v1.LocationR\bcentroid\"X\n" +
	"\x15SuggestCitiesResponse\x12?\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x1d.activities.v1.CitySuggestionR\vsuggestions\"\xd6\x01\n" +
	"\x15ListActivitiesRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x123\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x17.activities.v1.CategoryR\bcategory\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.activities.v1.ActivityStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"y\n" +
	"\x13ListActivitiesStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1c\n" +
	"\tpublished\x18\x02 \x01(\x05R\tpublished\x12\x14\n" +
	"\x05draft\x18\x03 \x01(\x05R\x05draft\x12\x18\n" +
	"\apending\x18\x04 \x01(\x05R\apending\"\xd2\x01\n" +
	"\x16ListActivitiesResponse\x127\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x17.activities.v1.ActivityR\n" +
	"activities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x128\n" +
	"\x05stats\x18\x05 \x01(\v2\".activities.v1.ListActivitiesStatsR\x05stats\"$\n" +
	"\x12GetActivityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18GetActivityPhotosRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x19GetActivityPhotosResponse\x12,\n" +
	"\x06photos\x18\x01 \x03(\v2\x14.activities.v1.PhotoR\x06photos\"\x18\n" +
	"\x16ListAdminCitiesRequest\"1\n" +
	"\x17ListAdminCitiesResponse\x12\x16\n" +
	"\x06cities\x18\x01 \x03(\tR\x06cities\"I\n" +
	"\x12UploadPhotoRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"D\n" +
	"\x13UploadPhotoResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tthumb_url\x18\x02 \x01(\tR\bthumbUrl\"\xd3\x02\n" +
	"\x15CreateActivityRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x123\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x17.activities.v1.CategoryR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x125\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1d.activities.v1.ActivityStatusR\x06status\x12\x18\n" +
	"\adetails\x18\a \x01(\tR\adetails\x12,\n" +
	"\x06photos\x18\b \x03(\v2\x14.activities.v1.PhotoR\x06photos\x12 \n" +
	"\vsubcategory\x18\t \x01(\tR\vsubcategory\"9\n" +
	"\tPhotoList\x12,\n" +
	"\x06photos\x18\x01 \x03(\v2\x14.activities.v1.PhotoR\x06photos\"\xf2\x03\n" +
	"\x15UpdateActivityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x128\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x17.activities.v1.CategoryH\x02R\bcategory\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x05 \x01(\tH\x03R\x04city\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x06 \x01(\tH\x04R\aaddress\x88\x01\x01\x12:\n" +
	"\x06status\x18\a \x01(\x0e2\x1d.activities.v1.ActivityStatusH\x05R\x06status\x88\x01\x01\x12\x1d\n" +
	"\adetails\x18\b \x01(\tH\x06R\adetails\x88\x01\x01\x120\n" +
	"\x06photos\x18\t \x01(\v2\x18.activities.v1.PhotoListR\x06photos\x12%\n" +
	"\vsubcategory\x18\n" +
	" \x01(\tH\aR\vsubcategory\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_categoryB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_addressB\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_detailsB\x0e\n" +
	"\f_subcategory*s\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSCOPE_NEARBY\x10\x02\x12\x12\n" +
	"\x0eSCOPE_ANYWHERE\x10\x04\"\x04\b\x01\x10\x01\"\x04\b\x03\x10\x03*\n" +
	"SCOPE_HOME*\x15SCOPE_OUTSIDE_COUNTRY*\xcb\x02\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CATEGORY_RESTAURANTS\x10\x01\x12\x12\n" +
	"\x0eCATEGORY_CAFES\x10\x02\x12\x11\n" +
	"\rCATEGORY_BARS\x10\x03\x12\x16\n" +
	"\x12CATEGORY_NIGHTLIFE\x10\x04\x12\x13\n" +
	"\x0fCATEGORY_NATURE\x10\x05\x12\x12\n" +
	"\x0eCATEGORY_SPORT\x10\x06\x12\x11\n" +
	"\rCATEGORY_KIDS\x10\a\x12\x14\n" +
	"\x10CATEGORY_CULTURE\x10\b\x12\x10\n" +
	"\fCATEGORY_ART\x10\t\x12\x15\n" +
	"\x11CATEGORY_WELLNESS\x10\n" +
	"\x12\x15\n" +
	"\x11CATEGORY_SHOPPING\x10\v\x12\x1a\n" +
	"\x16CATEGORY_ENTERTAINMENT\x10\f\x12\x1e\n" +
	"\x1aCATEGORY_TOURS_EXPERIENCES\x10\r*\x88\x01\n" +
	"\x0eActivityStatus\x12\x1f\n" +
	"\x1bACTIVITY_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ACTIVITY_STATUS_PUBLISHED\x10\x01\x12\x19\n" +
	"\x15ACTIVITY_STATUS_DRAFT\x10\x02\x12\x1b\n" +
	"\x17ACTIVITY_STATUS_PENDING\x10\x032\x97\a\n" +
	"\x11ActivitiesService\x12`\n" +
	"\x0fQueryActivities\x12%.activities.v1.QueryActivitiesRequest\x1a&.activities.v1.QueryActivitiesResponse\x12Z\n" +
	"\rSuggestCities\x12#.activities.v1.SuggestCitiesRequest\x1a$.activities.v1.SuggestCitiesResponse\x12]\n" +
	"\x0eListActivities\x12$.activities.v1.ListActivitiesRequest\x1a%.activities.v1.ListActivitiesResponse\x12I\n" +
	"\vGetActivity\x12!.activities.v1.GetActivityRequest\x1a\x17.activities.v1.Activity\x12f\n" +
	"\x11GetActivityPhotos\x12'.activities.v1.GetActivityPhotosRequest\x1a(.activities.v1.GetActivityPhotosResponse\x12X\n" +
	"\x1aGetActivityWithLiveDetails\x12!.activities.v1.GetActivityRequest\x1a\x17.activities.v1.Activity\x12O\n" +
	"\x0eCreateActivity\x12$.activities.v1.CreateActivityRequest\x1a\x17.activities.v1.Activity\x12O\n" +
	"\x0eUpdateActivity\x12$.activities.v1.UpdateActivityRequest\x1a\x17.activities.v1.Activity\x12`\n" +
	"\x0fListAdminCities\x12%.activities.v1.ListAdminCitiesRequest\x1a&.activities.v1.ListAdminCitiesResponse\x12T\n" +
	"\vUploadPhoto\x12!.activities.v1.UploadPhotoRequest\x1a\".activities.v1.UploadPhotoResponseB1Z/backend/shared/proto/activities/v1;activitiesv1b\x06proto3"

var (
	file_activities_v1_activities_proto_rawDescOnce sync.Once
	file_activities_v1_activities_proto_rawDescData []byte
)

func file_activities_v1_activities_proto_rawDescGZIP() []byte {
	file_activities_v1_activities_proto_rawDescOnce.Do(func() {
		file_activities_v1_activities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activities_v1_activities_proto_rawDesc), len(file_activities_v1_activities_proto_rawDesc)))
	})
	return file_activities_v1_activities_proto_rawDescData
}

var file_activities_v1_activities_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_activities_v1_activities_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_activities_v1_activities_proto_goTypes = []any{
	(Scope)(0),                        // 0: activities.v1.Scope
	(Category)(0),                     // 1: activities.v1.Category
	(ActivityStatus)(0),               // 2: activities.v1.ActivityStatus
	(*Location)(nil),                  // 3: activities.v1.Location
	(*Photo)(nil),                     // 4: activities.v1.Photo
	(*QueryActivitiesRequest)(nil),    // 5: activities.v1.QueryActivitiesRequest
	(*Activity)(nil),                  // 6: activities.v1.Activity
	(*GoogleAuthorAttribution)(nil),   // 7: activities.v1.GoogleAuthorAttribution
	(*GoogleReview)(nil),              // 8: activities.v1.GoogleReview
	(*QueryActivitiesResponse)(nil),   // 9: activities.v1.QueryActivitiesResponse
	(*SuggestCitiesRequest)(nil),      // 10: activities.v1.SuggestCitiesRequest
	(*CitySuggestion)(nil),            // 11: activities.v1.CitySuggestion
	(*SuggestCitiesResponse)(nil),     // 12: activities.v1.SuggestCitiesResponse
	(*ListActivitiesRequest)(nil),     // 13: activities.v1.ListActivitiesRequest
	(*ListActivitiesStats)(nil),       // 14: activities.v1.ListActivitiesStats
	(*ListActivitiesResponse)(nil),    // 15: activities.v1.ListActivitiesResponse
	(*GetActivityRequest)(nil),        // 16: activities.v1.GetActivityRequest
	(*GetActivityPhotosRequest)(nil),  // 17: activities.v1.GetActivityPhotosRequest
	(*GetActivityPhotosResponse)(nil), // 18: activities.v1.GetActivityPhotosResponse
	(*ListAdminCitiesRequest)(nil),    // 19: activities.v1.ListAdminCitiesRequest
	(*ListAdminCitiesResponse)(nil),   // 20: activities.v1.ListAdminCitiesResponse
	(*UploadPhotoRequest)(nil),        // 21: activities.v1.UploadPhotoRequest
	(*UploadPhotoResponse)(nil),       // 22: activities.v1.UploadPhotoResponse
	(*CreateActivityRequest)(nil),     // 23: activities.v1.CreateActivityRequest
	(*PhotoList)(nil),                 // 24: activities.v1.PhotoList
	(*UpdateActivityRequest)(nil),     // 25: activities.v1.UpdateActivityRequest
}
var file_activities_v1_activities_proto_depIdxs = []int32{
	0,  // 0: activities.v1.QueryActivitiesRequest.scope:type_name -> activities.v1.Scope
	3,  // 1: activities.v1.QueryActivitiesRequest.current_location:type_name -> activities.v1.Location
	1,  // 2: activities.v1.QueryActivitiesRequest.categories:type_name -> activities.v1.Category
	3,  // 3: activities.v1.QueryActivitiesRequest.cities:type_name -> activities.v1.Location
	1,  // 4: activities.v1.Activity.category:type_name -> activities.v1.Category
	3,  // 5: activities.v1.Activity.location:type_name -> activities.v1.Location
	4,  // 6: activities.v1.Activity.photos:type_name -> activities.v1.Photo
	2,  // 7: activities.v1.Activity.status:type_name -> activities.v1.ActivityStatus
	8,  // 8: activities.v1.Activity.google_reviews:type_name -> activities.v1.GoogleReview
	7,  // 9: activities.v1.GoogleReview.author_attribution:type_name -> activities.v1.GoogleAuthorAttribution
	6,  // 10: activities.v1.QueryActivitiesResponse.activities:type_name -> activities.v1.Activity
	3,  // 11: activities.v1.CitySuggestion.centroid:type_name -> activities.v1.Location
	11, // 12: activities.v1.SuggestCitiesResponse.suggestions:type_name -> activities.v1.CitySuggestion
	1,  // 13: activities.v1.ListActivitiesRequest.category:type_name -> activities.v1.Category
	2,  // 14: activities.v1.ListActivitiesRequest.status:type_name -> activities.v1.ActivityStatus
	6,  // 15: activities.v1.ListActivitiesResponse.activities:type_name -> activities.v1.Activity
	14, // 16: activities.v1.ListActivitiesResponse.stats:type_name -> activities.v1.ListActivitiesStats
	4,  // 17: activities.v1.GetActivityPhotosResponse.photos:type_name -> activities.v1.Photo
	1,  // 18: activities.v1.CreateActivityRequest.category:type_name -> activities.v1.Category
	2,  // 19: activities.v1.CreateActivityRequest.status:type_name -> activities.v1.ActivityStatus
	4,  // 20: activities.v1.CreateActivityRequest.photos:type_name -> activities.v1.Photo
	4,  // 21: activities.v1.PhotoList.photos:type_name -> activities.v1.Photo
	1,  // 22: activities.v1.UpdateActivityRequest.category:type_name -> activities.v1.Category
	2,  // 23: activities.v1.UpdateActivityRequest.status:type_name -> activities.v1.ActivityStatus
	24, // 24: activities.v1.UpdateActivityRequest.photos:type_name -> activities.v1.PhotoList
	5,  // 25: activities.v1.ActivitiesService.QueryActivities:input_type -> activities.v1.QueryActivitiesRequest
	10, // 26: activities.v1.ActivitiesService.SuggestCities:input_type -> activities.v1.SuggestCitiesRequest
	13, // 27: activities.v1.ActivitiesService.ListActivities:input_type -> activities.v1.ListActivitiesRequest
	16, // 28: activities.v1.ActivitiesService.GetActivity:input_type -> activities.v1.GetActivityRequest
	17, // 29: activities.v1.ActivitiesService.GetActivityPhotos:input_type -> activities.v1.GetActivityPhotosRequest
	16, // 30: activities.v1.ActivitiesService.GetActivityWithLiveDetails:input_type -> activities.v1.GetActivityRequest
	23, // 31: activities.v1.ActivitiesService.CreateActivity:input_type -> activities.v1.CreateActivityRequest
	25, // 32: activities.v1.ActivitiesService.UpdateActivity:input_type -> activities.v1.UpdateActivityRequest
	19, // 33: activities.v1.ActivitiesService.ListAdminCities:input_type -> activities.v1.ListAdminCitiesRequest
	21, // 34: activities.v1.ActivitiesService.UploadPhoto:input_type -> activities.v1.UploadPhotoRequest
	9,  // 35: activities.v1.ActivitiesService.QueryActivities:output_type -> activities.v1.QueryActivitiesResponse
	12, // 36: activities.v1.ActivitiesService.SuggestCities:output_type -> activities.v1.SuggestCitiesResponse
	15, // 37: activities.v1.ActivitiesService.ListActivities:output_type -> activities.v1.ListActivitiesResponse
	6,  // 38: activities.v1.ActivitiesService.GetActivity:output_type -> activities.v1.Activity
	18, // 39: activities.v1.ActivitiesService.GetActivityPhotos:output_type -> activities.v1.GetActivityPhotosResponse
	6,  // 40: activities.v1.ActivitiesService.GetActivityWithLiveDetails:output_type -> activities.v1.Activity
	6,  // 41: activities.v1.ActivitiesService.CreateActivity:output_type -> activities.v1.Activity
	6,  // 42: activities.v1.ActivitiesService.UpdateActivity:output_type -> activities.v1.Activity
	20, // 43: activities.v1.ActivitiesService.ListAdminCities:output_type -> activities.v1.ListAdminCitiesResponse
	22, // 44: activities.v1.ActivitiesService.UploadPhoto:output_type -> activities.v1.UploadPhotoResponse
	35, // [35:45] is the sub-list for method output_type
	25, // [25:35] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_activities_v1_activities_proto_init() }
func file_activities_v1_activities_proto_init() {
	if File_activities_v1_activities_proto != nil {
		return
	}
	file_activities_v1_activities_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activities_v1_activities_proto_rawDesc), len(file_activities_v1_activities_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activities_v1_activities_proto_goTypes,
		DependencyIndexes: file_activities_v1_activities_proto_depIdxs,
		EnumInfos:         file_activities_v1_activities_proto_enumTypes,
		MessageInfos:      file_activities_v1_activities_proto_msgTypes,
	}.Build()
	File_activities_v1_activities_proto = out.File
	file_activities_v1_activities_proto_goTypes = nil
	file_activities_v1_activities_proto_depIdxs = nil
}
